### ISSUE TITLE
Two Letter Country Names = ?

### ISSUE THREAD

**Issue by quantum9Innovation** [epispot/covid19-tracker#3]
Two letter country names have probably been interpreted as two separate parameters and therefore the correct case data has not been fetched for these countries.

**Comment by Quantalabs** [comment]
The problem here is that discord.py only takes in one word for each param, so if you type "New Zealand" the program reads it as "New" and ignores the rest. The solution would be to take to arguments, and then combine the two arguments when running it through the API.
